#ifndef DISPLAY_CONFIG_H
#define DISPLAY_CONFIG_H

#define DISPLAY_SPI_HOST SPI2_HOST

#define DISPLAY_WIDTH 320
#define DISPLAY_HEIGHT 240

#define DISPLAY_PIN_BACKLIGHT 26
#define DISPLAY_PIN_MOSI 16
#define DISPLAY_PIN_SCLK 4
#define DISPLAY_PIN_CS 18
#define DISPLAY_PIN_DC 5
#define DISPLAY_PIN_RST 17

#define DISPLAY_SPI_FREQUENCY_HZ 27000000
#define DISPLAY_BACKLIGHT_ON_LEVEL 1

#define DISPLAY_RGB_ORDER_BGR 1

#define DISPLAY_SWAP_XY 1
#define DISPLAY_MIRROR_X 1
#define DISPLAY_MIRROR_Y 0
#define DISPLAY_INVERT_COLOR 1
#define DISPLAY_GAP_X 0
#define DISPLAY_GAP_Y 0

#endif
