#ifndef DISPLAY_WEATHER_ICON_TYPES_H
#define DISPLAY_WEATHER_ICON_TYPES_H

typedef enum {
    WEATHER_ICON_UNKNOWN = 0,
    WEATHER_ICON_CLEAR_DAY = 1,
    WEATHER_ICON_CLEAR_NIGHT = 2,
    WEATHER_ICON_CLOUDY_DAY = 3,
    WEATHER_ICON_CLOUDY_NIGHT = 4,
    WEATHER_ICON_OVERCAST = 5,
    WEATHER_ICON_LIGHT_RAIN = 6,
    WEATHER_ICON_MODERATE_RAIN = 7,
    WEATHER_ICON_HEAVY_RAIN = 8,
    WEATHER_ICON_SHOWER = 9,
    WEATHER_ICON_THUNDERSTORM = 10,
    WEATHER_ICON_SNOW = 11,
    WEATHER_ICON_FOG = 12,
    WEATHER_ICON_HAZE = 13,
    WEATHER_ICON_DUST_STORM = 14,
    WEATHER_ICON_WINDY = 15,
} weather_icon_kind_t;

#endif
